version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
    restart: on-failure


volumes:
  postgres_data:

